package constants

const (
	PUBLIC_API_KEY           = "PUBLIC_API"
	ELASTIC_URL              = "ELASTIC_URL"
	PORT                     = "PORT"
	CLOUD_STORAGE_NAME       = "CLOUD_STORAGE_NAME"
	CLOUD_STORAGE_API_KEY    = "CLOUD_STORAGE_API_KEY"
	CLOUD_STORAGE_API_SECRET = "CLOUD_STORAGE_API_SECRET"
)
